export const WIDGET_LAYOUT_STATE_ID = "DASHBOARD/WIDGET_LAYOUT_STATE";
export const WIDGET_LAYOUT_PLACEHOLDER_ID =
  "DASHBOARD/WIDGET_LAYOUT_PLACEHOLDER";
export const LAYOUT_PLACEHOLDER_CONFIG = {
  i: WIDGET_LAYOUT_PLACEHOLDER_ID,
  x: 0,
  y: 0,
  w: 0,
  h: 0,
  minW: 0,
  minH: 0,
  static: true,
};
